name: "minecraft_server_status"

services:
    minecraft_server_status:
        container_name: "minecraft_server_status"
        image: "ghcr.io/9-fs/minecraft_server_status:latest"
        mem_limit: "1G"
        volumes:
            - "/mnt/user/appdata/minecraft_server_status/config/:/app/config/"
            - "/mnt/user/appdata/minecraft_server_status/log/:/app/log/"