version: "3"

services:
    minecraft_server_status:
        container_name: "minecraft_server_status"
        image: "ghcr.io/9-fs/minecraft_server_status:3.1.0"
        environment:
            HOST_OS: "Unraid"
            TZ: "UTC"
        volumes:
            - "/mnt/user/appdata/minecraft_server_status/config/:/app/config/:rw"
            - "/mnt/user/appdata/minecraft_server_status/log/:/app/log/:rw"
        network_mode: "bridge"
        deploy:
            resources:
                limits:
                    memory: "1G"
        user: "99:100"

networks: {}